### ISSUE TITLE
Manually placed points should be automatically refined

### ISSUE THREAD

**Issue by ctrueden** [fiji/Simple_Neurite_Tracer#1]
From @mhl:

> At the moment the points you manually specify are considered fixed, so won't be adjusted by the "Fit Volume" option, for example.  This is a limitation that I intend to fix, but it needs a bit of careful work.  There are two plans I have for this:
> - Allow manual adjustment of where the points are at any stage
> - Allowing the fitting to adjust the manually placed points as well as the intermediate points
> 
> In the mean time, my suggestion would be to select the intermediate points in a zoomed-in view, using the three-pane view to find the midline of the neuron.  There's a short tutorial here explaining what I mean:
> 
>    http://fiji.sc/Simple_Neurite_Tracer:_Accurate_point_placement

Migrated-From: http://fiji.sc/bugzilla/show_bug.cgi?id=222

**Comment by tferr** [comment]
This could be tackled in multiple ways. v3.1.0 implements a snap-to function in which the cursor will automatically 'sniff' for local maxima and 'snap' to their average X,Y,Z position. This functionallity was inspired by [NeuronJ](https://imagej.net/NeuronJ). Here is a description from its [manual](https://imagescience.org/meijering/software/neuronj/manual/) (accessed 2016.12.30):

> To facilitate accurate positioning of starting points, so that they are really on a neurite rather than close to one, the program carries out a local snapping operation. This means that when moving the mouse within the image, the program quickly searches in a small window around the current mouse position for the pixel that is most likely to be on a neurite. This position is indicated by the red cross-hair cursor which is behind the real, white cross-hair cursor.

But in SNT, this functionality works in 3D (there is an option in the GUI to restrict it to 2D if needed).

So, I consider this issue now closed. It could be reopened if someone feels otherwise.
