### ISSUE TITLE
Release workflow?

### ISSUE THREAD

**Issue by tferr** [fiji/Simple_Neurite_Tracer#24]
@ctrueden, I was trying to release a new version (as I've done in the past: 1) commit directly to master the version in the pom 2) uploading the jar and 3) increment the version back to SNAPSHOT in pom.

I just did 1) with 2fca2f4 but the build failed. It seems that things changed since I last did this. I also noticed that the github releases page seems to be automatically populated (before I was creating releases there by hand).. What is the new procedure?

**Comment by ctrueden** [comment]
This is the same issue as with tferr/ASA#22: the build is trying to deploy the `-sources` JAR twice, so it fails the second time. I'm sorry I haven't had time to investigate the best way to fix this. Maybe the `exists-maven-plugin` is the simplest solution.

Regarding the GitHub releases page: I think it just populates a stub entry with each tag you push? I think some Googling around should yield more information about it.

**Comment by tferr** [comment]
Thanks. 
> I think it just populates a stub entry with each tag you push?

You are right that seems to be the case. Somehow I thought otherwise.

@ctrueden, if there are no problems with it, I will upload it to the java 8 update site and close this

**Comment by ctrueden** [comment]
> I will upload it to the java 8 update site and close this

Sorry for the delay in reply; definitely go ahead and upload new releases as needed for the time being.

If you want to be extra helpful, you can also file a PR against [pom-scijava](https://github.com/scijava/pom-scijava) updating your component(s) to the new release versions, too. But if you don't do it, I will, since [this page](http://status.scijava.org/) (updated manually for the moment, but soon programmatically at least daily) tells me when versions in pom-scijava are outdated.

Some day (before end of 2017, perhaps?) I would like to switch to a scheme whereby the versions given by the [fiji/fiji](https://github.com/fiji/fiji) repository fully drive what is on the update site. But I want to complete the transition to Java-8 first and get rid of the Java-8 update site, so that `fiji/fiji` drives the Fiji site, and `imagej/imagej` drives the ImageJ site, as one would presume.

**Comment by tferr** [comment]
Perfect! Just uploaded to the Java8 update site. And sincere thanks for the detailed update. Closing this. BTW, see also https://github.com/scijava/pom-scijava/pull/45
