### ISSUE TITLE
Importing neuronstudio SWC files

### ISSUE THREAD

**Issue by ctrueden** [fiji/Simple_Neurite_Tracer#36]
From a [message to the ImageJ mailing list](https://list.nih.gov/cgi-bin/wa.exe?A2=IMAGEJ;d68f3acd.1805):

> Currently in our department we are trying to find a standardized method of tracing neurons received from stacks. We generate the stacks and any substacks within Fiji and once we have a target neuron we import the stacks into Neuronstudio to trace it, as Neuronstudio can automatically trace. After saving these traces in an swc file we try to reload it into Fiji Simple Neurite tracer, however we always encounter an issue with scaling. We always have the correct offset coordinates at hand, previously saved from the original stacks in Fiji, but the offset scaling is always off, sometimes really off. The tracings always appear smaller than the original. With trial and error we can come as close as possible to the correct scaling but this is rather time consuming and the endgoal is to fully automate the whole process via standard procedures for a protocol, that will be used in the lab. Would anybody know if what the precise error is or how to work around it?

**Comment by tferr** [comment]
I have been trying to reproduce this for a while now, with no success.

**Comment by ctrueden** [comment]
The original poster never commented here, nor followed up with any more details or steps to reproduce, so I'd vote to close this.

**Comment by tferr** [comment]
OK. Hopefully, the problem is just related to the lack of documentation on import options. I will try to address that with #47. When one imports SWC coordinates, SNT considers (as per SWC specification) that such coordinates are expressed in real-world units (um, mm, etc.). If that is not the case, one needs to toggle the "assume SWC uses pixel coordinates" in the import prompt.

![image](https://user-images.githubusercontent.com/2439948/55277440-a10d6780-52d6-11e9-9cb4-f7fbdf95f0c2.png)
