### ISSUE TITLE
Release SNT

### ISSUE THREAD

**Issue by tferr** [fiji/Simple_Neurite_Tracer#46]
:tada: !!SNT is finally ready to be released!! :tada: 
Because the program changed significantly, we would rename it to SNT. The change may sound silly but it highlights the effort that was put into backward compatibility and makes the point that the program is no longer that _Simple_ :wink: 

Also, I see a couple of issues that we should look into before the release:

- [x] Dependencies: [json](https://mvnrepository.com/artifact/org.json/json) does not follow SemVer
- [x] Dependencies: jzy3d-api [required by us](https://github.com/fiji/Simple_Neurite_Tracer/blob/scijava/pom.xml#L240-L242) is a SNAPSHOT version
- [x] ~~Impact on other projects: Last time I checked, [TrakEM2](https://github.com/trakem2/TrakEM2) was using SNT, so we'll have to make sure things still work there. I will be looking into it, but Pinging @axtimwalde for now, for a heads-up~~. This is addressed with https://github.com/trakem2/TrakEM2/pull/25

@ctrueden, how can we achieve this and release SNT v0.0.1? (or is it v.0.9.0-SNAPHOT?). I'm assuming it is just not enough to rename the project. Can you help us assemble a todo list fo this?

**Comment by axtimwalde** [comment]
Ping forward to @acardona

**Comment by tferr** [comment]
@ctrueden, just a friendly ping in case you've missed this

**Comment by ctrueden** [comment]
The `json` dependency not being SemVer is not a big deal. We just need to be cautious about when we update to new versions of that library across the Fiji component stack.

The `jzy3d-api` dependencies needs to be on a non-SNAPSHOT release, yeah—ideally throughout the entire git history. Otherwise, those old commits will stop building in the future, which would be a shame.

For the rename, have you considered backronyming the SNT to something new like "Super Neurite Tracer", rather than leaving the name opaque?

Regarding naming on the technical side:
* The git repository here on GitHub can be renamed without issue—a redirect will be created from the old repo.
* Renaming the artifact is fine—we'll just obsolete the old `Simple_Neurite_Tracer` and then start shipping the new `SNT` or whatever it ends up being.
* Would be ideal if the package prefix became `sc.fiji.snt` or similar. Right now Fiji plugins have a hodgepodge of package prefixes, but we're slowly working toward standardizing all prefixes to `sc.fiji`.
* The above assumes that SNT is going to remain a Fiji plugin—i.e., that it will continue to ship with Fiji. If that is the case, we need to first solve the fact that it depends on SciView, and SciView is not currently distributed with Fiji. @kephale is the plan for SciView to become part of the standard Fiji distribution?

Does that help? Maybe we should schedule one or more video calls to go over status, plan out tasks, etc.? Or we can just discuss here and do that, if you prefer.

**Comment by ctrueden** [comment]
One thing I didn't talk about above: whether to do a rename, vs. a fork. If we fork to a new SNT repo, but keep this repository as-is in minimal maintenance mode, that would preserve backwards compatibility more completely. But at the expense of the old menu commands lying around forever cluttering things up. If the new SNT strives to be backwards API compatible (does it?), then we can probably get away with a rename. Was that the idea?

**Comment by kephale** [comment]
I think SciView will need to become a part of the standard Fiji distribution, but that would not be appropriate until at least the next major SciView release.

My vote is for Smart Neurite Tracer.

**Comment by tferr** [comment]
@ctrueden, @kephale, thanks!
I like the opaqueness of SNT :) will have to think a bit more about it. 

> If the new SNT strives to be backwards API compatible (does it?), then we can probably get away with a rename. Was that the idea?

Yes. From the user side (GUI, workflows, etc.) especially. Programmatically I don't think it is a problem. the (very few) methods that could run in the absence of the GUI were maintained (like the one trakEM2 uses), all others would not be useful anyway, and I never found anyone using them. Having legacy and modern side-by-side looks more of a burden, and I really wanted to avoid having to deal with it.

> I think SciView will need to become a part of the standard Fiji distribution, but that would not be appropriate until at least the next major SciView release.

Yes! But I don't see a problem here also. Right now SNT is released through the NeuroAnatomy update site. While we are in this pre-release limbo, we could keep it as is, then both SNT and SciView could go to the Java8 update site.

> Does that help? Maybe we should schedule one or more video calls to go over status, plan out tasks, etc.? Or we can just discuss here and do that, if you prefer.

It does. Thanks for the time! that would be great, perhaps we could schedule one when @kephale is on campus so that we save bandwith :) But first, give me some time start with the `sc.fiji.snt` and the snapshot dependencies, then I will be able to have a more well-defined to-do list. I'll ping you guys here

**Comment by tferr** [comment]
Closing as discussion is now at https://github.com/morphonets/SNT/issues/20
